#!/bin/bash
# Regenerates /etc/nginx/snippets/irongate-access.conf from
# /etc/irongate/access-control.json, validates, and reloads nginx.
# Called via sudo by the WebUI (www-data) after allow-list changes.
# Every entry is re-validated here as root — the JSON is group-writable by
# www-data and must never be able to inject arbitrary nginx directives.
set -euo pipefail

CONF="/etc/nginx/snippets/irongate-access.conf"
JSON="/etc/irongate/access-control.json"
TMP="${CONF}.tmp.$$"
PREV="/run/irongate-access.prev.$$"

{
echo "# Auto-generated by irongate auth system - do not edit manually"
echo "# Managed via WebUI Security > IP Allow-List"
echo "# Regenerated by /opt/irongate/regen-access.sh"
if [ -f "$JSON" ]; then
php -r '
$acl = json_decode(@file_get_contents($argv[1]), true);
if ($acl && !empty($acl["enabled"]) && !empty($acl["allowed_ips"]) && is_array($acl["allowed_ips"])) {
    foreach ($acl["allowed_ips"] as $ip) {
        $ip = trim((string)$ip);
        $ok = false;
        if (filter_var($ip, FILTER_VALIDATE_IP)) {
            $ok = true;
        } elseif (preg_match("#^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})$#", $ip, $m)) {
            $ok = intval($m[5]) <= 32;
            for ($i = 1; $i <= 4; $i++) { if (intval($m[$i]) > 255) { $ok = false; } }
        }
        if ($ok) { echo "allow " . $ip . ";\n"; }
    }
    echo "deny all;\n";
} else {
    echo "# IP allow-list disabled - all IPs permitted (auth still required)\n";
}
' "$JSON"
else
echo "# no access-control.json - all IPs permitted (auth still required)"
fi
} > "$TMP"

cp -p "$CONF" "$PREV" 2>/dev/null || true
mv "$TMP" "$CONF"
chown root:root "$CONF"
chmod 644 "$CONF"

if ! nginx -t 2>&1; then
    if [ -f "$PREV" ]; then mv "$PREV" "$CONF"; fi
    echo "ERROR: nginx config test failed; previous access list restored" >&2
    exit 1
fi
rm -f "$PREV"
systemctl reload-or-restart nginx
